language: python
python:
  - 3.7
before_install:
  - python --version
  - pip install -U pip 
  - pip install -U pytest
  - pip install pytest-cov
  - pip install coveralls
script: 
  - pytest --cov=src/ 
after_success:
  - coveralls --verbose